#!/usr/bin/env python
# -*- coding:utf8 -*-

from mcheck import main
import sys
import signal


def intur_hander(signal, frame):
    sys.exit(0)

if __name__ == "__main__":
    signal.signal(signal.SIGINT, intur_hander)
    main.run()


